os:
  - linux
  - osx
matrix:
  fast_finish: true
os:
  - linux
  - osx
notifications:
  email:
    - beehivecloud@gmail.com
branches:
  only:
    - master
    - stable
    - beta
before_script:
  - npm install nan@1.8.4
  - npm install -g node-gyp
  - git submodule init
  - git submodule update
  - cd vendor/libgit2
  - git checkout v0.23.1
  - cd ../..
  - mkdir build
  - cd build
script:
  - cmake ..
  - cmake --build .
