language: cpp
compiler: gcc
os:
  - linux
env:
  matrix:
    - export NODE_VERSION="0.12"
notifications:
  email:
    - beehivecloud@gmail.com
before_install:
  - npm install nan@1.8.4
  - npm install -g node-gyp
  - export NODE_GYP_VER="0.12.5"
  - export NODE_GYP_DIR="~/.node-gyp"
  - export LIBMYSQL_INCLUDE_DIR="/usr/local/include/mysql"
  - export LIBMYSQL_LIBRARY="/usr/local/lib64/mysql"
  - export LD_LIBRARY_PATH="$LIBMYSQL_LIBRARY:$LD_LIBRARY_PATH"
before_script:
  - git submodule init
  - git submodule update
  - cd vendor/libgit2
  - git checkout v0.23.1
  - cd ../..
  - mkdir build
  - cd build
  - git clone https://github.com/JerryYangJin/hello.git
  - cd hello
  - node-gyp configure
  - cd ..
  - rm -rf hello
script:
  - cmake ..
  - cmake --build .
