# http://www.appveyor.com/docs/appveyor-yml

environment:
  # set variables
  NODE_GYP_VER: 0.12.7
  LIBMYSQL_INCLUDE_DIR: C:\Program Files\MySql\MySQL Server 5.6\include
  LIBMYSQL_LIBRARY: C:\Program Files\MySql\MySQL Server 5.6\lib

  matrix:
    - nodejs_version: "0.12"

platform:
  - x64

configuration:
  - Release

install:
  - set NODE_GYP_DIR=%USERPROFILE%\.node-gyp
  - npm install nan@1.8.4

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version

build:
  project: c:\projects\honeycomb\build\honeycomb.sln

before_build:
  - git submodule init
  - git submodule update
  - cd vendor/libgit2
  - git checkout v0.23.0
  - md build
  - cd c:\projects\honeycomb\build
  - cmake ..

artifacts:
  - path: c:\projects\honeycomb\build\Release\addon.node
