# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
  # node.js
    - nodejs_version: "0.12"

# Install scripts. (runs after repo cloning)
install:
  # Typical npm stuff.
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
