# http://www.appveyor.com/docs/appveyor-yml

environment:
  # set variables
  NODE_GYP_VER: 0.12.7
  NODE_GYP_DIR: %USERPROFILE%\.node-gyp
  LIBMYSQL_INCLUDE_DIR: C:\Program Files\MySql\MySQL Server 5.6\include
  LIBMYSQL_LIBRARY: C:\Program Files\MySql\MySQL Server 5.6\lib

  matrix:
    - nodejs_version: "0.12"

platform:
  - x86

configuration:
  - Release

install:
  - npm install nan@1.8.4

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version

build:
  project: c:\projects\honeycomb\build\honeycomb.sln

before_build:
  - echo Running cmake...
  - cd c:\projects\honeycomb\build
  - cmake ..

artifacts:
  - path: c:\projects\honeycomb\build\Release\addon.node
