DROP TABLE IF EXISTS `GIT_REPO`;

CREATE TABLE GIT_REPO(
  `id` SERIAL,
  `owner` BIGINT UNSIGNED NOT NULL,
   `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `ts` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX (`owner`,`name`)
)
ENGINE = "InnoDB"
DEFAULT CHARSET = utf8
COLLATE = utf8_bin;
