#  LIBNODE_INCLUDE_DIR - where to find node.h, etc.
#  LIBNODE_LIBRARY     - List of libraries when using node.
#  LIBNODE_FOUND       - True if node found.

#  Read environment variables to find mysql include/lib directories
SET(LIBNODE_INCLUDE_DIR $ENV{LIBNODE_INCLUDE_DIR})
MESSAGE( STATUS "LIBNODE_INCLUDE_DIR:         " ${LIBNODE_INCLUDE_DIR} )
SET(LIBNODE_LIBRARY $ENV{LIBNODE_LIBRARY})
MESSAGE( STATUS "LIBNODE_LIBRARY:         " ${LIBNODE_LIBRARY} )
SET(LIBUV_INCLUDE_DIR $ENV{LIBUV_INCLUDE_DIR})
MESSAGE( STATUS "LIBUV_INCLUDE_DIR:         " ${LIBUV_INCLUDE_DIR} )
SET(LIBV8_INCLUDE_DIR $ENV{LIBV8_INCLUDE_DIR})
MESSAGE( STATUS "LIBV8_INCLUDE_DIR:         " ${LIBV8_INCLUDE_DIR} )

FIND_PATH(LIBNODE_INCLUDE_DIR node.h)
FIND_PATH(LIBUV_INCLUDE_DIR uv.h)
FIND_PATH(LIBV8_INCLUDE_DIR v8.h)
FIND_LIBRARY(LIBNODE_LIBRARY node)

# handle the QUIETLY and REQUIRED arguments and set Libnode_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBNODE DEFAULT_MSG LIBNODE_LIBRARY LIBNODE_INCLUDE_DIR)

MARK_AS_ADVANCED(LIBNODE_LIBRARY LIBNODE_INCLUDE_DIR LIBUV_INCLUDE_DIR LIBV8_INCLUDE_DIR)
