#  HADOOP_INCLUDE_DIR
#  HADOOP_LIBRARY
#  HADOOP_FOUND

SET(JAVA_HOME $ENV{JAVA_HOME})
MESSAGE( STATUS "JAVA_HOME:         " ${JAVA_HOME} )
SET(HADOOP_INCLUDE_DIR $ENV{HADOOP_HOME}/include)
MESSAGE( STATUS "HADOOP_INCLUDE_DIR:         " ${HADOOP_INCLUDE_DIR} )
SET(HADOOP_LIBRARY $ENV{HADOOP_HOME}/bin)
MESSAGE( STATUS "HADOOP_LIBRARY:         " ${HADOOP_LIBRARY} )

FIND_PATH(HADOOP_INCLUDE_DIR hdfs.h)

FIND_LIBRARY(HADOOP_LIBRARY hadoop)

# handle the QUIETLY and REQUIRED arguments and set Libmysql_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(HADOOP DEFAULT_MSG HADOOP_INCLUDE_DIR HADOOP_LIBRARY)

MARK_AS_ADVANCED(HADOOP_INCLUDE_DIR HADOOP_LIBRARY)
